### ISSUE TITLE
User can create idea.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/date-night#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a date night idea.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click a button to create a new date night idea.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-21 at 9 39 57 AM](https://user-images.githubusercontent.com/82188718/126526493-459d953d-96cb-42ae-b36f-78a82f8f9fc9.png) ![Screen Shot 2021-07-21 at 9 39 47 AM](https://user-images.githubusercontent.com/82188718/126526498-782f5cda-0149-4149-83a6-574e074555d4.png)

![Screen Shot 2021-07-21 at 9 56 57 AM](https://user-images.githubusercontent.com/82188718/126528793-bc5dff5e-48c2-44c5-9b1a-6d138d5b7bb6.png) ![Screen Shot 2021-07-21 at 9 57 05 AM](https://user-images.githubusercontent.com/82188718/126528801-20c76312-9376-4e6d-b661-9190d07df3b8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] 'schema.sql' setup
- [x] Update `data.sql` to include some dummy data.

### ☁️ Server

- [x] Update `server/index.js` to handle a POST method to create an idea.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the header with the app title.
- [x] Create a component for the nav bar.
- [x] Create a component for the idea creation form.
- [x] Create an idea when the user clicks 'add'.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
