### ISSUE TITLE
User can view upcoming dates.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/date-night#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their upcoming dates.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the 'upcoming' page, the upcoming dates will be listed along with the date information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-27 at 9 41 45 PM](https://user-images.githubusercontent.com/82188718/127264911-5d4dc4f8-1d30-4865-b55c-436675338b89.png) ![Screen Shot 2021-07-27 at 9 41 53 PM](https://user-images.githubusercontent.com/82188718/127264921-d99133b3-6fdc-4b7d-b320-e6e058c5b368.png)
![Screen Shot 2021-07-27 at 9 34 02 PM](https://user-images.githubusercontent.com/82188718/127264701-842ee6db-ed4c-4238-86f4-f6aec906c155.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a 'GET' method for dates that are scheduled.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a fetch request within app.jsx to get all upcoming dates. 
- [x] Update the state to include an array of all upcoming dates.
- [x] Create a component for the upcoming dates.
- [x] Pass the array of upcoming dates as a prop to the 'upcoming' component.
- [x] Update the component to render all upcoming dates passed as a prop.
- [x] Complete the CSS styling for the 'upcoming' elements on both mobile and desktop.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
