### ISSUE TITLE
User can view past dates.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/date-night#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view dates from the past.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On the 'my dates' page, the user will be able to view a list of all past dates and info.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-28 at 4 23 18 PM](https://user-images.githubusercontent.com/82188718/127408668-c9c70168-b06e-4d88-ae8b-4b337f2cceca.png) ![Screen Shot 2021-07-28 at 4 23 26 PM](https://user-images.githubusercontent.com/82188718/127408672-c7dd6e9f-b926-4e9b-ac35-b32e59fd5787.png) ![Screen Shot 2021-07-28 at 4 23 36 PM](https://user-images.githubusercontent.com/82188718/127408675-8a959c8e-45fa-4d6c-9376-adfc1739ff94.png) ![Screen Shot 2021-07-28 at 4 14 47 PM](https://user-images.githubusercontent.com/82188718/127408099-a7c21e33-2c04-4251-a703-1f6960d522c4.png) ![Screen Shot 2021-07-28 at 4 15 05 PM](https://user-images.githubusercontent.com/82188718/127408104-4f31a661-f157-4bf9-b3ca-67815f91209f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a get request to ideas that are scheduled.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render all past dates.
- [x] Filter through dates for dates that are in the past.
- [x] If user clicks on date, they will be directed to a page with the date details.
- [x] Ensure that styling is formatted for both mobile and desktop.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
