### ISSUE TITLE
User can edit past date.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/date-night#15]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a past date.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

From the 'my-dates
From the 'my-dates' page, users will be able to edit their past dates. They will be able to change already existing info including title, description, location, and schedule. In addition to this, they will be able to add new information, including experience notes and photo uploads.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-29 at 10 26 17 AM](https://user-images.githubusercontent.com/82188718/127537509-de194e8e-c096-4d45-b560-2bd862bfbc6c.png) ![Screen Shot 2021-07-29 at 10 26 53 AM](https://user-images.githubusercontent.com/82188718/127537516-bb14b8e7-f7a9-4ba6-979f-6155bd1b1e8b.png) ![Screen Shot 2021-07-29 at 10 27 13 AM](https://user-images.githubusercontent.com/82188718/127537518-776ce942-2ea8-476f-906a-9bf86f2eb86d.png) ![Screen Shot 2021-07-29 at 10 27 23 AM](https://user-images.githubusercontent.com/82188718/127537525-4f8efac2-7232-4e8e-8857-a52507c42894.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a 'PUT' method for the past dates.
- [x] Within the new method, user should be able to update the ideas table, locations table, and schedule table.
- [x] User should also be able to post new information to the notes table and the images table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component that contains the 'edit date' form.
- [x] The form should have a title input, location, description, scheduling inputs, notes input, and photo upload inputs.
- [x] When the user clicks 'edit' on a past date, they should be redirected to the form.
- [x] The form should be pre-populated with any existing data.

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
