### ISSUE TITLE
User can view ideas.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/date-night#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their created date ideas.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to see a list of their date night ideas along with information regarding each idea.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-21 at 9 39 24 AM](https://user-images.githubusercontent.com/82188718/126527166-738726f3-462e-4007-8681-f315339de5b8.png) ![Screen Shot 2021-07-21 at 9 39 38 AM](https://user-images.githubusercontent.com/82188718/126527187-c4ddae81-802c-40cb-8ee8-4436887eee34.png) ![Screen Shot 2021-07-21 at 9 46 49 AM](https://user-images.githubusercontent.com/82188718/126527341-fa34cddd-d3bc-409c-82ca-37025dafe4c6.png)

![Screen Shot 2021-07-21 at 9 57 15 AM](https://user-images.githubusercontent.com/82188718/126528957-e87a9ad7-1a3b-49d4-969f-352322632872.png) ![Screen Shot 2021-07-21 at 9 57 30 AM](https://user-images.githubusercontent.com/82188718/126529006-c47640ab-409e-4ba1-9cf2-87d29c2003bb.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle a GET method to get ideas.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create fetch request to retrieve all ideas.
- [x] Create a component to render each idea.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
