### ISSUE TITLE
User can edit idea.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/date-night#3]
## ⚙️ Feature

User can edit an idea.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click a button to edit any idea. It will take them to the idea form with the idea information pre-populated into the form, where they can then make and save changes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-24 at 8 44 06 PM](https://user-images.githubusercontent.com/82188718/126887042-3513ce10-30b9-4f0c-ac89-a6e5f3bb278c.png) ![Screen Shot 2021-07-24 at 8 43 52 PM](https://user-images.githubusercontent.com/82188718/126887043-2505e523-c60c-4560-b828-908100b5387d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a 'PUT' method to update an idea.
- [x] Test with HTTPie.
- [x] Handle all errors and respond to the client.

### ⚡ Client

- [x] Create a component that includes the idea form.
- [x] Update component to include an 'edit idea' title.
- [x] Update hash routing so whenever an 'edit' button on an idea is clicked, the user is directed to the edit form page.
- [x] Update the 'add' button to an 'update' button if the user is on the 'edit-idea' page.
- [x] Update the 'cancel' button to a 'delete' button if the user is on the 'edit-idea' page.
- [x] Pre-populate the idea form with the idea information to be edited when the user clicks 'edit'.
- [x] Send a fetch request to the server for the 'PUT' method when the user clicks 'update'.
- [x] Ensure that the user is redirected to their ideas and that the edited idea has been updated.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
