### ISSUE TITLE
User can delete idea.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/date-night#7]
## ⚙️ Feature

User will be able to delete a date night idea.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
From the edit-idea page, the user will be able to click 'delete'. A modal will the appear asking the user to either confirm or cancel their delete. If they choose to cancel, the modal will disappear. If they choose to delete, the idea will be deleted and the user will be redirected to the ideas page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-26 at 5 09 47 PM](https://user-images.githubusercontent.com/82188718/127074839-c90b5dab-50d5-43ca-a5ce-eaf982667a9c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a delete method.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the delete confirmation modal.
- [x] When the user clicks the delete button from the edit-idea page, the modal should appear.
- [x] If the user clicks out of the modal or clicks 'cancel', the modal should disappear.
- [x] Create a fetch request for the delete method.
- [x] If the user clicks the delete method, the fetch request should be triggered.
- [x] Ensure that the idea has been deleted and the user has been redirected to their ideas.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
