### ISSUE TITLE
User can set calendar date.

### ISSUE THREAD

**Issue by alessandragutierrez** [alessandragutierrez/date-night#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to set a calendar day and time for a date night idea.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click a button to set a date, which will trigger a modal to appear where they can input the month, day, and time. After they submit the calendar date, the date night idea will then be moved to the 'upcoming' page. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-07-27 at 10 55 10 AM](https://user-images.githubusercontent.com/82188718/127203979-ca94df99-ad9c-47ee-a28d-dc94df806e2f.png) ![Screen Shot 2021-07-27 at 10 55 20 AM](https://user-images.githubusercontent.com/82188718/127203989-6b19978f-be25-445a-8cc7-ebce32ed7d88.png) ![Screen Shot 2021-07-27 at 10 55 32 AM](https://user-images.githubusercontent.com/82188718/127203997-2d04e25f-bf4f-4d25-b22c-15d95e1a3d6a.png)
![Screen Shot 2021-07-27 at 10 56 08 AM](https://user-images.githubusercontent.com/82188718/127204013-93958516-8d02-49e7-b75e-71dc7c8abb8c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include a post method to for the schedule table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the 'set a date' modal.
- [x] Update the component for include a form for the month, day, and time.
- [x] Create a fetch request to the post method for the schedule table.
- [x] When the user submits the form, the fetch request will be triggered.
- [x] Ensure that the idea is no longer in the ideas page.
- [x] Ensure that the user is redirected to their upcoming dates.
- [x] Ensure that if the user clicked out of the modal or clicked 'cance'l, they were redirected to the previous page.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
